# Generated by Django 3.1.5 on 2021-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20200808_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='position',
            field=models.IntegerField(blank=True, default=0, verbose_name='Position'),
        ),
    ]
