# Generated by Django 3.1.5 on 2021-04-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20210310_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_boolean',
            field=models.BooleanField(default=False, verbose_name='processed_boolean'),
        ),
    ]
