
# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python38

instance_class: B4

service: gbbe1

basic_scaling:
  max_instances: 11
  idle_timeout: 5m  # default is 5m
  
env_variables:
  DEBUG: 1
  SECRET_KEY: vW?,N"u~Ms7[=RqXC8?5x@.[t]W8FVdH8m}(u~Mc
  DJANGO_ALLOWED_HOSTS: gbbe1-dot-thinking-glass-282301.uc.r.appspot.com .gbbe1.thinking-glass-282301.uc.r.appspot.com [::1]
  SQL_HOST: /cloudsql/thinking-glass-282301:us-central1:gbdb1
  SQL_PORT: 5432
  SQL_ENGINE: django.db.backends.postgresql
  SQL_DATABASE: postgres
  SQL_USER: postgres
  SQL_PASSWORD: o40y6f37hjc9H885
  STATIC_URL: https://storage.cloud.google.com/gb-s/static/
  SITE_ID: 3
  GOOGLE_APPLICATION_CREDENTIALS: thinking-glass-282301-1175a1e8d2c6.json
  CLOUD_TASKS: True
  MYQUEUE: vidprocessor0
  MYPROJECT: thinking-glass-282301
  MYLOCATION: us-central1

handlers:
  # should match requests to /static to https://storage.cloud.google.com/gb-s/static/
  # not sure if it actually works or if what is in settings.py is making static work
  - url: /static
    static_dir: https://storage.cloud.google.com/gb-s/static/
    secure: always
  - url: /.*
    script: auto
    secure: always
